services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      networks:
        - foeder-network
    environment:
      - IN_DOCKER=true
    volumes:
      - .:/app                    
      - /app/node_modules           
    ports:
      - "5173:5173"                

